name: pull-request-comment

on:
  issue_comment:
    types:
      - 'created'

jobs:
  tag-with-comment:
    if: github.event.issue.state == 'open' && github.event.issue.pull_request && contains(github.event.comment.body, '/release-storybook')
    runs-on: ubuntu-latest

    steps:
      - name: 🧰 set node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: install depenency
        run:

      - name: 🗂 build storybook
        run: yarn run build:storybook

      - name: 🛫 deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CSE_NPM_TOKEN }}
          publish_dir: ./dist/storybook
