name: pull-request-comment

on:
  issue_comment:
    types:
      - 'created'

jobs:
  tag-with-comment:
    if: github.event.issue.state == 'open' && github.event.issue.pull_request && contains(github.event.comment.html_url, '/test')
    runs-on: ubuntu-latest

    env:
      CSE_NPM_TOKEN: ${{secrets.CSE_NPM_TOKEN}}

    steps:
      - name: 🧰 use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - uses: actions/checkout@v3
        with:
          token: ${{secrets.CSE_NPM_TOKEN}}

      - name: 🗂 build storybook
        run: yarn build:storybook

      - name: 🛫 deploy storybook
        run: yarn deploy:storybook
